/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface": "#1b1b1b",
        "inverse-on-surface": "#f3f0ef",
        outline: "#717973",
        "secondary-container": "#aeeecb",
        "on-primary-container": "#86af99",
        "error-container": "#ffdad6",
        "outline-variant": "#c1c8c2",
        "tertiary-fixed-dim": "#85d7ad",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#c1ecd4",
        "on-secondary-fixed": "#002114",
        primary: {
          DEFAULT: "#012d1d",
          foreground: "#ffffff",
          container: "#1b4332",
          "on-container": "#86af99",
        },
        tertiary: {
          DEFAULT: "#002d1c",
          container: "#00452d",
          "on-container": "#64b68e",
        },
        "primary-fixed-dim": "#a5d0b9",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#274e3d",
        "on-tertiary-container": "#64b68e",
        "on-background": "#1b1b1b",
        "on-error-container": "#93000a",
        "surface-variant": "#e5e2e1",
        "inverse-surface": "#313030",
        "surface-bright": "#fcf9f8",
        "surface-container": "#f0eded",
        "surface-container-highest": "#e5e2e1",
        "primary-container": "#1b4332",
        "on-primary": "#ffffff",
        "inverse-primary": "#a5d0b9",
        "on-secondary-container": "#316e52",
        "secondary-fixed": "#b1f0ce",
        "surface-container-low": "#f6f3f2",
        "tertiary-container": "#00452d",
        surface: {
          DEFAULT: "#fcf9f8",
          dim: "#dcd9d9",
          bright: "#fcf9f8",
          lowest: "#ffffff",
          low: "#f6f3f2",
          container: "#f0eded",
          high: "#eae7e7",
          highest: "#e5e2e1",
          variant: "#e5e2e1",
          tint: "#3f6653",
        },
        "secondary-fixed-dim": "#95d4b3",
        "on-error": "#ffffff",
        secondary: {
          DEFAULT: "#2c694e",
          foreground: "#ffffff",
          container: "#aeeecb",
          "on-container": "#316e52",
        },
        background: "#fcf9f8",
        foreground: "#1b1b1b",
        "tertiary-fixed": "#a0f4c8",
        "on-secondary-fixed-variant": "#0e5138",
        "surface-dim": "#dcd9d9",
        "on-surface-variant": "#414844",
        "surface-container-high": "#eae7e7",
        "surface-tint": "#3f6653",
        "on-primary-fixed": "#002114",
        "surface-container-lowest": "#ffffff",
        card: {
          DEFAULT: "#ffffff",
          foreground: "#1b1b1b",
        },
        border: "#c1c8c2",
        input: "#c1c8c2",
        ring: "#1b4332",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        base: "4px",
        xl: "32px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        gutter: "20px",
        xs: "4px",
        lg: "24px",
        md: "16px",
        "2xl": "48px",
        "3xl": "64px",
        "4xl": "96px",
        "5xl": "128px",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        "display-xl": ['"Plus Jakarta Sans"', "sans-serif"],
        "display-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-lg-mobile": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-md": ['"Plus Jakarta Sans"', "sans-serif"],
        "body-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "body-md": ['"Plus Jakarta Sans"', "sans-serif"],
        "label-md": ['"Plus Jakarta Sans"', "sans-serif"],
        "label-sm": ['"Plus Jakarta Sans"', "sans-serif"],
      },
      fontSize: {
        "display-xl": [
          "64px",
          { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "700" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "28px", fontWeight: "400" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "24px", fontWeight: "400" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", fontWeight: "500" },
        ],
      },
      boxShadow: {
        card: "0px 4px 24px rgba(27,67,50,0.06)",
        "card-hover": "0px 12px 32px rgba(27,67,50,0.12)",
        button: "0px 4px 16px rgba(27,67,50,0.15)",
        soft: "0 10px 40px -10px rgba(0,0,0,0.08)",
        "level-1": "0 1px 3px 0 rgba(27, 67, 50, 0.05)",
        "level-2": "0px 4px 24px rgba(27, 67, 50, 0.06)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
